version: '3'
services:
  api:
    image: "node"
    user: "node"
    ports:
    - 1337:1337
    working_dir: /home/node/app
    volumes:
      - ./api:/home/node/app
    command: "npm run develop"
  db:
    image: "mariadb"
    ports:
    - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456